# Generated by Django 4.2 on 2026-05-06 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('botapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessagelog',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_logs', to='businesses.business'),
        ),
    ]
