# Generated by Django 4.2 on 2026-05-06 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_business_brand_color_business_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/logos/')),
                ('primary_color', models.CharField(default='#2563eb', max_length=20)),
                ('secondary_color', models.CharField(default='#0f172a', max_length=20)),
                ('hide_platform_branding', models.BooleanField(default=False)),
                ('custom_footer_text', models.CharField(blank=True, max_length=255)),
                ('custom_bot_welcome_message', models.TextField(blank=True)),
                ('custom_domain', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='businesses.business')),
            ],
        ),
    ]
