# Generated by Django 4.2 on 2026-05-06 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('auto_salon', 'Auto Salon'), ('education_center', 'Education Center'), ('shop', 'Shop'), ('restaurant', 'Restaurant'), ('clinic', 'Clinic'), ('beauty_salon', 'Beauty Salon'), ('service', 'Service'), ('real_estate', 'Real Estate')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business/logos/')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('working_hours', models.CharField(blank=True, max_length=255)),
                ('telegram_bot_token', models.CharField(blank=True, max_length=255)),
                ('telegram_admin_chat_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
