# Generated by Django 4.2 on 2026-05-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='brand_color',
            field=models.CharField(default='#2563eb', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='public_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='business',
            name='public_page_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
