# Generated by Django 4.2 on 2026-05-06 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_business_brand_color_business_hero_subtitle_and_more'),
        ('leads', '0003_lead_last_contacted_at_lead_next_follow_up_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('trigger_status', models.CharField(default='new', max_length=30)),
                ('delay_hours', models.PositiveIntegerField(default=1)),
                ('message_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_rules', to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_tasks', to='businesses.business')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_tasks', to='leads.lead')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='followups.followuprule')),
            ],
        ),
    ]
