# Generated by Django 4.2 on 2026-05-12 16:47

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_add_fitness_center'),
        ('catalog', '0002_item_education_catalog_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('unknown', "Ko'rsatilmagan"), ('male', 'Erkak'), ('female', 'Ayol')], default='unknown', max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('client_type', models.CharField(choices=[('daily', 'Kunlik'), ('monthly', 'Oylik')], db_index=True, default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('paused', "To'xtatilgan"), ('archived', 'Arxiv')], db_index=True, default='active', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='businesses.business')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClientMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('expected_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('currency', models.CharField(default='UZS', max_length=10)),
                ('sessions_total', models.PositiveIntegerField(default=0)),
                ('sessions_used', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('expiring', 'Muddati tugayapti'), ('expired', 'Muddati tugagan'), ('cancelled', 'Bekor qilingan')], db_index=True, default='active', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', "To'lanmagan"), ('partial', "Qisman to'langan"), ('paid', "To'langan")], db_index=True, default='unpaid', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='businesses.business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='memberships.businessclient')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='catalog.item')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClientPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('currency', models.CharField(default='UZS', max_length=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "O'tkazma"), ('other', 'Boshqa')], default='cash', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_payments', to='businesses.business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='memberships.businessclient')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='memberships.clientmembership')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClientAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('visit_time', models.TimeField(blank=True, null=True)),
                ('client_type', models.CharField(choices=[('daily', 'Kunlik'), ('monthly', 'Oylik')], db_index=True, default='monthly', max_length=20)),
                ('amount_charged', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Kunlik klient uchun to'lov summasi (oylik klientda 0 bo'lishi mumkin).", max_digits=15)),
                ('currency', models.CharField(default='UZS', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='businesses.business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='memberships.businessclient')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='memberships.clientmembership')),
            ],
            options={
                'ordering': ['-visit_date', '-visit_time', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='clientpayment',
            index=models.Index(fields=['business', 'payment_date'], name='memberships_busines_04c739_idx'),
        ),
        migrations.AddIndex(
            model_name='clientpayment',
            index=models.Index(fields=['client'], name='memberships_client__df1a14_idx'),
        ),
        migrations.AddIndex(
            model_name='clientmembership',
            index=models.Index(fields=['business', 'status'], name='memberships_busines_1c0a9c_idx'),
        ),
        migrations.AddIndex(
            model_name='clientmembership',
            index=models.Index(fields=['business', 'payment_status'], name='memberships_busines_d6ee46_idx'),
        ),
        migrations.AddIndex(
            model_name='clientmembership',
            index=models.Index(fields=['client', 'status'], name='memberships_client__a79879_idx'),
        ),
        migrations.AddIndex(
            model_name='clientattendance',
            index=models.Index(fields=['business', 'visit_date'], name='memberships_busines_8d4989_idx'),
        ),
        migrations.AddIndex(
            model_name='clientattendance',
            index=models.Index(fields=['client', 'visit_date'], name='memberships_client__74f946_idx'),
        ),
        migrations.AddIndex(
            model_name='businessclient',
            index=models.Index(fields=['business', 'client_type'], name='memberships_busines_7cfeef_idx'),
        ),
        migrations.AddIndex(
            model_name='businessclient',
            index=models.Index(fields=['business', 'status'], name='memberships_busines_802d1a_idx'),
        ),
    ]
