# Generated by Django 4.2 on 2026-05-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessclient',
            name='announcement',
            field=models.TextField(blank=True, help_text="Klient kabinetida ko'rinadigan xabar (eslatma, e'lon, tilak)."),
        ),
        migrations.AlterField(
            model_name='businessclient',
            name='note',
            field=models.TextField(blank=True, help_text="Ichki eslatma (faqat admin ko'radi)."),
        ),
    ]
