# Generated by Django 4.2 on 2026-05-06 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
        ('businesses', '0001_initial'),
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('appointment', 'Qabul'), ('test_drive', 'Test drive'), ('trial_lesson', 'Sinov darsi'), ('table_booking', 'Stol bron'), ('service_booking', 'Xizmat bron'), ('consultation', 'Konsultatsiya')], default='appointment', max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('guests_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('confirmed', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('completed', 'Bajarilgan'), ('cancelled', 'Bekor qilingan')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='businesses.business')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='city.city')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='customers.telegramcustomer')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='catalog.item')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
