# Generated by Django 4.2 on 2026-05-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('menu_config', models.JSONField(blank=True, default=dict)),
                ('prompt_template', models.TextField(blank=True)),
                ('lead_rules', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
