# Generated by Django 4.2 on 2026-05-06 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_entries', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='business_type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
