# Generated by Django 4.2 on 2026-05-10 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_rating'),
        ('edu_quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_count', models.PositiveSmallIntegerField()),
                ('total_questions', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='edu_quizzes.eduquiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='students.student')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='eduquizattempt',
            index=models.Index(fields=['student', '-created_at'], name='edu_quizzes_student_44e54b_idx'),
        ),
        migrations.AddIndex(
            model_name='eduquizattempt',
            index=models.Index(fields=['student', 'quiz', '-created_at'], name='edu_quizzes_student_fb0c81_idx'),
        ),
    ]
