# Generated by Django 4.2 on 2026-05-06 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice_type', models.CharField(choices=[('setup', 'O‘rnatish'), ('monthly', 'Oylik'), ('featured', 'Reklama'), ('extra_ai', 'Qo‘shimcha AI')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('unpaid', 'To‘lanmagan'), ('paid', 'To‘langan'), ('overdue', 'Muddati o‘tgan')], default='unpaid', max_length=20)),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='businesses.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
