# Generated by Django 4.2 on 2026-05-06 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(choices=[('demo', 'Demo'), ('start', 'Start'), ('business', 'Business'), ('premium', 'Premium')], max_length=20, unique=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('setup_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_items', models.PositiveIntegerField(default=10)),
                ('max_managers', models.PositiveIntegerField(default=1)),
                ('max_leads_per_month', models.PositiveIntegerField(default=30)),
                ('max_ai_messages_per_month', models.PositiveIntegerField(default=100)),
                ('has_ai_chat', models.BooleanField(default=True)),
                ('has_analytics', models.BooleanField(default=False)),
                ('has_public_page', models.BooleanField(default=False)),
                ('has_marketing_generator', models.BooleanField(default=False)),
                ('has_auto_followup', models.BooleanField(default=False)),
                ('has_white_label', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Sinov'), ('active', 'Faol'), ('overdue', 'Muddati o‘tgan'), ('cancelled', 'Bekor qilingan')], default='trial', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='businesses.business')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
