# Generated by Django 4.2 on 2026-05-10 05:34

from decimal import Decimal

from django.db import migrations, models


def set_demo_start_trials(apps, schema_editor):
    """Demo — 7 kunlik bepul sinov, cheklovlar Startdan past; Start — sinovsiz to‘lovli."""
    Plan = apps.get_model("subscriptions", "SubscriptionPlan")
    Plan.objects.filter(code="demo").update(
        trial_days=7,
        name="Demo",
        monthly_price=Decimal("0"),
        setup_price=Decimal("0"),
        max_items=20,
        max_managers=1,
        max_leads_per_month=100,
        max_ai_messages_per_month=250,
        has_ai_chat=True,
        has_analytics=False,
        has_public_page=True,
        has_marketing_generator=False,
        has_auto_followup=False,
        has_white_label=False,
        has_edu_attendance=True,
        has_edu_materials=True,
        has_edu_portals=True,
        parent_can_create_student_portal=False,
        is_active=True,
    )
    Plan.objects.filter(code="start").update(
        trial_days=0,
        name="Start",
        monthly_price=Decimal("149000"),
        setup_price=Decimal("0"),
        max_items=120,
        max_managers=4,
        max_leads_per_month=1500,
        max_ai_messages_per_month=4000,
        has_ai_chat=True,
        has_analytics=False,
        has_public_page=True,
        has_marketing_generator=False,
        has_auto_followup=False,
        has_white_label=False,
        has_edu_attendance=True,
        has_edu_materials=True,
        has_edu_portals=True,
        parent_can_create_student_portal=False,
        is_active=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_subscriptionplan_parent_student_portal"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="trial_days",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="0 = sinovsiz. Demo: odatda 7 — bepul sinov muddati (kun).",
            ),
        ),
        migrations.RunPython(set_demo_start_trials, migrations.RunPython.noop),
    ]
