# Generated by Django 4.2 on 2026-05-06 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='UZS', max_length=10)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='new', max_length=10)),
                ('body_type', models.CharField(blank=True, max_length=50)),
                ('fuel_type', models.CharField(blank=True, max_length=50)),
                ('transmission', models.CharField(blank=True, max_length=50)),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('has_credit', models.BooleanField(default=False)),
                ('has_trade_in', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('hidden', 'Hidden')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/')),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
        ),
    ]
