/** @type {Record<string, object>} */
export const BUSINESS_TYPE_CONFIG = {
  auto_salon: {
    label: "Avtosalon",
    color: "#0EA5E9",
    gradient: "linear-gradient(135deg, #0EA5E9, #06B6D4)",
    icon: "Car",
    itemLabel: "Mashina",
    itemsLabel: "Mashinalar",
    leadsLabel: "Mijoz so'rovlari",
    bookingsLabel: "Test drive",
    dashboardTitle: "Avtosalon boshqaruvi",
  },
  education_center: {
    label: "O'quv markaz",
    color: "#7C3AED",
    gradient: "linear-gradient(135deg, #7C3AED, #A78BFA)",
    icon: "GraduationCap",
    itemLabel: "Kurs",
    itemsLabel: "Kurslar",
    leadsLabel: "O'quvchi arizalari",
    bookingsLabel: "Sinov darslar",
    dashboardTitle: "O'quv markaz paneli",
  },
  shop: {
    label: "Do'kon",
    color: "#F97316",
    gradient: "linear-gradient(135deg, #F97316, #FB923C)",
    icon: "ShoppingBag",
    itemLabel: "Mahsulot",
    itemsLabel: "Mahsulotlar",
    leadsLabel: "Mijoz so'rovlari",
    ordersLabel: "Buyurtmalar",
    dashboardTitle: "Do'kon boshqaruvi",
  },
  restaurant: {
    label: "Restoran",
    color: "#F97316",
    gradient: "linear-gradient(135deg, #EA580C, #F59E0B)",
    icon: "UtensilsCrossed",
    itemLabel: "Taom",
    itemsLabel: "Menyu",
    leadsLabel: "Buyurtma so'rovlari",
    bookingsLabel: "Stol bronlari",
    ordersLabel: "Buyurtmalar",
    dashboardTitle: "Restoran boshqaruvi",
  },
  clinic: {
    label: "Klinika",
    color: "#06B6D4",
    gradient: "linear-gradient(135deg, #06B6D4, #22D3EE)",
    icon: "Stethoscope",
    itemLabel: "Xizmat",
    itemsLabel: "Xizmatlar",
    leadsLabel: "Murojaatlar",
    bookingsLabel: "Qabul arizalari",
    dashboardTitle: "Klinika paneli",
  },
  beauty_salon: {
    label: "Go'zallik saloni",
    color: "#EC4899",
    gradient: "linear-gradient(135deg, #EC4899, #F472B6)",
    icon: "Sparkles",
    itemLabel: "Xizmat",
    itemsLabel: "Xizmatlar",
    leadsLabel: "Murojaatlar",
    bookingsLabel: "Navbatlar",
    dashboardTitle: "Salon boshqaruvi",
  },
  repair_service: {
    label: "Usta xizmatlari",
    color: "#16A34A",
    gradient: "linear-gradient(135deg, #16A34A, #22C55E)",
    icon: "Wrench",
    itemLabel: "Xizmat",
    itemsLabel: "Xizmatlar",
    leadsLabel: "Murojaatlar",
    bookingsLabel: "Xizmat buyurtmalari",
    ordersLabel: "Buyurtmalar",
    dashboardTitle: "Usta xizmatlari",
  },
  real_estate: {
    label: "Ko'chmas mulk",
    color: "#2563EB",
    gradient: "linear-gradient(135deg, #2563EB, #3B82F6)",
    icon: "Building2",
    itemLabel: "Uy",
    itemsLabel: "Uylar",
    leadsLabel: "Mijoz so'rovlari",
    bookingsLabel: "Uchrashuvlar",
    dashboardTitle: "Ko'chmas mulk",
  },
  taxi_delivery: {
    label: "Taxi / yetkazib berish",
    color: "#F59E0B",
    gradient: "linear-gradient(135deg, #F59E0B, #FBBF24)",
    icon: "Truck",
    itemLabel: "Xizmat",
    itemsLabel: "Xizmatlar",
    leadsLabel: "Murojaatlar",
    bookingsLabel: "So'rovlar",
    ordersLabel: "Buyurtmalar",
    dashboardTitle: "Yetkazib berish",
  },
  fitness_center: {
    label: "Fitness zal",
    color: "#2563EB",
    gradient: "linear-gradient(135deg, #2563EB, #06B6D4)",
    icon: "Dumbbell",
    itemLabel: "Abonement",
    itemsLabel: "Abonementlar",
    leadsLabel: "Abonement arizalari",
    bookingsLabel: "Sinov mashg'ulotlar",
    dashboardTitle: "Fitness CRM",
  },
  fitness: {
    label: "Fitnes",
    color: "#2563EB",
    gradient: "linear-gradient(135deg, #2563EB, #06B6D4)",
    icon: "Dumbbell",
    itemLabel: "Abonement",
    itemsLabel: "Abonementlar",
    leadsLabel: "Arizalar",
    dashboardTitle: "Fitness CRM",
  },
  legal_service: {
    label: "Yuridik xizmat",
    color: "#64748B",
    gradient: "linear-gradient(135deg, #475569, #64748B)",
    icon: "Scale",
    itemLabel: "Xizmat",
    itemsLabel: "Xizmatlar",
    leadsLabel: "Murojaatlar",
    bookingsLabel: "Konsultatsiyalar",
    dashboardTitle: "Yuridik xizmat",
  },
  photo_video: {
    label: "Foto / video",
    color: "#8B5CF6",
    gradient: "linear-gradient(135deg, #8B5CF6, #A78BFA)",
    icon: "Camera",
    itemLabel: "Xizmat",
    itemsLabel: "Xizmatlar",
    leadsLabel: "Murojaatlar",
    bookingsLabel: "Bronlar",
    ordersLabel: "Buyurtmalar",
    dashboardTitle: "Foto / video",
  },
  custom: {
    label: "Boshqa",
    color: "#64748B",
    gradient: "linear-gradient(135deg, #2563EB, #06B6D4)",
    icon: "LayoutGrid",
    itemLabel: "Pozitsiya",
    itemsLabel: "Xizmatlar",
    leadsLabel: "Murojaatlar",
    dashboardTitle: "Biznes paneli",
  },
};

export function getBusinessTypeConfig(type) {
  return BUSINESS_TYPE_CONFIG[type] || BUSINESS_TYPE_CONFIG.custom;
}
