/** @type {Record<string, { label: string; color: string; itemLabel: string; itemsLabel: string; leadsLabel: string; bookingsLabel?: string; ordersLabel?: string }>} */
export const BUSINESS_TYPE_CONFIG = {
  auto_salon: {
    label: "Avtosalon",
    color: "#2563eb",
    itemLabel: "Mashina",
    itemsLabel: "Mashinalar",
    leadsLabel: "Mijoz so‘rovlari",
    bookingsLabel: "Test drive",
  },
  education_center: {
    label: "O‘quv markaz",
    color: "#722ed1",
    itemLabel: "Kurs",
    itemsLabel: "Kurslar",
    leadsLabel: "O‘quvchi arizalari",
    bookingsLabel: "Sinov darslar",
  },
  shop: {
    label: "Do‘kon",
    color: "#fa8c16",
    itemLabel: "Mahsulot",
    itemsLabel: "Mahsulotlar",
    leadsLabel: "Mijoz so‘rovlari",
    ordersLabel: "Buyurtmalar",
  },
  restaurant: {
    label: "Restoran",
    color: "#eb2f96",
    itemLabel: "Taom",
    itemsLabel: "Menyu",
    leadsLabel: "Buyurtma so‘rovlari",
    bookingsLabel: "Bronlar",
    ordersLabel: "Buyurtmalar",
  },
  clinic: {
    label: "Klinika",
    color: "#13c2c2",
    itemLabel: "Xizmat",
    itemsLabel: "Xizmatlar",
    leadsLabel: "Lidlar",
    bookingsLabel: "Qabul arizalari",
  },
  beauty_salon: {
    label: "Go‘zallik saloni",
    color: "#f759ab",
    itemLabel: "Xizmat",
    itemsLabel: "Xizmatlar",
    leadsLabel: "Lidlar",
    bookingsLabel: "Navbatlar",
  },
  repair_service: {
    label: "Usta xizmatlari",
    color: "#52c41a",
    itemLabel: "Xizmat",
    itemsLabel: "Xizmatlar",
    leadsLabel: "Lidlar",
    bookingsLabel: "Xizmat buyurtmalari",
    ordersLabel: "Buyurtmalar",
  },
  real_estate: {
    label: "Ko‘chmas mulk",
    color: "#2f54eb",
    itemLabel: "Uy",
    itemsLabel: "Uylar",
    leadsLabel: "Mijoz so‘rovlari",
    bookingsLabel: "Uchrashuvlar",
  },
  taxi_delivery: {
    label: "Taxi / yetkazib berish",
    color: "#faad14",
    itemLabel: "Xizmat",
    itemsLabel: "Xizmatlar",
    leadsLabel: "Lidlar",
    bookingsLabel: "So‘rovlar",
    ordersLabel: "Buyurtmalar",
  },
  fitness: {
    label: "Fitnes",
    color: "#389e0d",
    itemLabel: "Xizmat",
    itemsLabel: "Xizmatlar",
    leadsLabel: "Arizalar",
  },
  fitness_center: {
    label: "Fitness zal",
    color: "#15803d",
    icon: "Dumbbell",
    itemLabel: "Abonement",
    itemsLabel: "Abonementlar",
    leadsLabel: "Abonement arizalari",
    bookingsLabel: "Sinov mashg‘ulotlar",
  },
  legal_service: {
    label: "Yuridik xizmat",
    color: "#595959",
    itemLabel: "Xizmat",
    itemsLabel: "Xizmatlar",
    leadsLabel: "Murojaatlar",
    bookingsLabel: "Konsultatsiyalar",
  },
  photo_video: {
    label: "Foto / video",
    color: "#9254de",
    itemLabel: "Xizmat",
    itemsLabel: "Xizmatlar",
    leadsLabel: "Lidlar",
    bookingsLabel: "Bronlar",
    ordersLabel: "Buyurtmalar",
  },
  custom: {
    label: "Boshqa",
    color: "#8c8c8c",
    itemLabel: "Pozitsiya",
    itemsLabel: "Xizmatlar",
    leadsLabel: "Lidlar",
  },
};

export function getBusinessTypeConfig(type) {
  return BUSINESS_TYPE_CONFIG[type] || BUSINESS_TYPE_CONFIG.custom;
}
