# Generated by Django 4.2 on 2026-05-08 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentgroup_teacher'),
        ('teachers', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='portal_student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_user_account', to='students.student'),
        ),
        migrations.AddField(
            model_name='user',
            name='portal_teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_user_account', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super admin'), ('business_owner', 'Biznes egasi'), ('manager', 'Menejer'), ('edu_teacher', 'O‘quv markaz ustozi'), ('edu_student', 'O‘quv markaz o‘quvchisi')], default='business_owner', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('portal_teacher__isnull', True), ('portal_student__isnull', True), _connector='OR'), name='accounts_user_portal_at_most_one'),
        ),
    ]
