# Generated by Django 4.2 on 2026-05-12 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_businessclient_announcement_and_more'),
        ('accounts', '0003_user_edu_parent_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='portal_business_client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_user_account', to='memberships.businessclient'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super admin'), ('business_owner', 'Biznes egasi'), ('manager', 'Menejer'), ('edu_teacher', 'O‘quv markaz ustozi'), ('edu_student', 'O‘quv markaz o‘quvchisi'), ('edu_parent', 'O‘quv markaz ota-onasi'), ('business_client', 'Biznes klienti')], default='business_owner', max_length=20),
        ),
    ]
