# Generated by Django 4.2 on 2026-05-06 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businesses', '0001_initial'),
        ('city', '0001_initial'),
        ('catalog', '0001_initial'),
        ('service_categories', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('general', 'Umumiy'), ('car_interest', 'Mashina qiziqishi'), ('credit', 'Kredit'), ('test_drive', 'Test drive'), ('trade_in', 'Trade-in'), ('contact', 'Aloqa'), ('course_register', 'Kursga yozilish'), ('order', 'Buyurtma'), ('custom', 'Boshqa')], default='general', max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('contacted', 'Aloqa qilindi'), ('interested', 'Qiziqish'), ('negotiation', 'Musobaqa'), ('completed', 'Yakunlangan'), ('won', 'Uttim'), ('lost', 'Yutqazildi'), ('cancelled', 'Bekor qilindi')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Past'), ('medium', 'O‘rta'), ('high', 'Yuqori')], default='medium', max_length=10)),
                ('source', models.CharField(choices=[('telegram_bot', 'Telegram bot'), ('public_page', 'Ochiq sahifa'), ('manual', 'Qo‘lda')], default='telegram_bot', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='businesses.business')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='service_categories.servicecategory')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='city.city')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='customers.telegramcustomer')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='catalog.item')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
