# Generated by Django 4.2 on 2026-05-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_add_membership_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('telegram_bot', 'Telegram bot'), ('public_page', 'Ochiq sahifa'), ('manual', 'Qo‘lda'), ('instagram', 'Instagram')], default='telegram_bot', max_length=20),
        ),
    ]
