# Generated by Django 4.2 on 2026-05-08 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('students', '0002_studentgroup_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_groups', to='teachers.teacher'),
        ),
    ]
