# Generated by Django 4.2 on 2026-05-09 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentgroup_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Masalan: Matematika — oraliq nazorat', max_length=200)),
                ('points', models.PositiveSmallIntegerField(help_text='0 dan 100 gacha ball')),
                ('comment', models.TextField(blank=True)),
                ('rated_at', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='students.student')),
            ],
            options={
                'ordering': ['-rated_at', '-created_at', 'id'],
            },
        ),
    ]
