# Generated by Django 4.2 on 2026-05-06 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('icon', models.CharField(blank=True, help_text='Emoji yoki icon identifikatori', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('category_type', models.CharField(choices=[('auto_salon', 'Avtosalon'), ('education_center', 'O‘quv markaz'), ('shop', 'Do‘kon'), ('restaurant', 'Restoran'), ('clinic', 'Klinika'), ('beauty_salon', 'Go‘zallik saloni'), ('repair_service', 'Usta xizmatlari'), ('real_estate', 'Uy-joy'), ('taxi_delivery', 'Taxi / yetkazib berish'), ('fitness', 'Fitnes'), ('legal_service', 'Yuridik xizmat'), ('photo_video', 'Foto / video'), ('event', 'Tadbirlar'), ('hotel', 'Mehmonxona'), ('tourism', 'Turizm'), ('car_rental', 'Avto ijarasi'), ('electronics_repair', 'Elektronika ta’miri'), ('cleaning', 'Tozalash'), ('custom', 'Boshqa')], default='custom', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('featured_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_categories', to='city.city')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('city', 'slug')},
            },
        ),
    ]
