# Generated by Django 4.2 on 2026-05-06 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
        ('businesses', '0001_initial'),
        ('service_categories', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('auto_salon', 'Avtosalon'), ('education_center', 'O‘quv markaz'), ('shop', 'Do‘kon'), ('restaurant', 'Restoran'), ('clinic', 'Klinika'), ('beauty_salon', 'Go‘zallik saloni'), ('repair_service', 'Usta xizmatlari'), ('real_estate', 'Uy-joy'), ('taxi_delivery', 'Taxi / yetkazib berish'), ('fitness', 'Fitnes'), ('legal_service', 'Yuridik xizmat'), ('photo_video', 'Foto / video'), ('event', 'Tadbirlar'), ('hotel', 'Mehmonxona'), ('tourism', 'Turizm'), ('car_rental', 'Avto ijarasi'), ('electronics_repair', 'Elektronika ta’miri'), ('cleaning', 'Tozalash'), ('custom', 'Boshqa')], max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('menu_config', models.JSONField(blank=True, default=dict)),
                ('field_config', models.JSONField(blank=True, default=dict)),
                ('prompt_template', models.TextField(blank=True)),
                ('lead_types', models.JSONField(blank=True, default=list)),
                ('booking_enabled', models.BooleanField(default=False)),
                ('order_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('category_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_sessions', to='city.city')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_sessions', to='customers.telegramcustomer')),
                ('selected_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_sessions', to='businesses.business')),
                ('selected_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_sessions', to='service_categories.servicecategory')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BotMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('intent', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_message_logs', to='businesses.business')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_message_logs', to='city.city')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_message_logs', to='customers.telegramcustomer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
