# Generated by Django 4.2 on 2026-05-06 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('businesses', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='lead',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='catalog.item'),
        ),
        migrations.AddField(
            model_name='lead',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
