# Generated by Django 4.2 on 2026-05-06 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('city', '0001_initial'),
        ('service_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=160)),
                ('business_type', models.CharField(choices=[('auto_salon', 'Avtosalon'), ('education_center', 'O‘quv markaz'), ('shop', 'Do‘kon'), ('restaurant', 'Restoran'), ('clinic', 'Klinika'), ('beauty_salon', 'Go‘zallik saloni'), ('repair_service', 'Usta xizmatlari'), ('real_estate', 'Uy-joy'), ('taxi_delivery', 'Taxi / yetkazib berish'), ('fitness', 'Fitnes'), ('legal_service', 'Yuridik xizmat'), ('photo_video', 'Foto / video'), ('event', 'Tadbirlar'), ('hotel', 'Mehmonxona'), ('tourism', 'Turizm'), ('car_rental', 'Avto ijarasi'), ('electronics_repair', 'Elektronika ta’miri'), ('cleaning', 'Tozalash'), ('custom', 'Boshqa')], default='custom', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business/logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='business/covers/')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('location_url', models.URLField(blank=True)),
                ('working_hours', models.CharField(blank=True, max_length=255)),
                ('telegram_admin_chat_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('active', 'Faol'), ('blocked', 'Bloklangan'), ('archived', 'Arxivlangan')], default='pending', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='service_categories.servicecategory')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='city.city')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Egasi'), ('manager', 'Menejer'), ('operator', 'Operator')], default='manager', max_length=20)),
                ('telegram_id', models.CharField(blank=True, max_length=50)),
                ('can_manage_items', models.BooleanField(default=True)),
                ('can_manage_leads', models.BooleanField(default=True)),
                ('can_manage_settings', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='businesses.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('business', 'user')},
            },
        ),
    ]
